name: '13'
timestamp: 1590934817
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1590928134
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-6519: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-7171: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-2844: Copyright
  social:
    social-2031: Social
  branding:
    branding-8758: Branding
  mobile-menu:
    mobile-menu-7603: 'Mobile Menu'
inherit: {  }
