version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1590928134
layout:
  /header/:
    -
      - 'logo-5959 15'
      - 'menu-6519 85'
  /navigation/:
    -
      - position-module-7108
    -
      - position-module-6880
    -
      - position-module-7360
  /showcase/: {  }
  /feature/:
    -
      - sample-4220
  /main/:
    -
      - system-messages-7171
    -
      - sample-9357
  /subfeature/:
    -
      - sample-3
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2844 33.3'
      - 'social-2031 33.3'
      - 'branding-8758 33.3'
  offcanvas:
    -
      - mobile-menu-7603
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: '2'
      class: ''
      variations: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-5959:
    title: 'Logo / Image'
    attributes:
      url: ''
      target: _self
      image: 'gantry-media://headers/logo_104x62.png'
      height: ''
      svg: ''
      class: star-logo
    block:
      fixed: '1'
  position-module-7108:
    title: 'Module Instance'
    attributes:
      module_id: '91'
      key: module-instance
  position-module-6880:
    title: 'Module Instance'
    attributes:
      module_id: '93'
      key: module-instance
  position-module-7360:
    title: 'Module Instance'
    attributes:
      module_id: '97'
      key: module-instance
  sample-4220:
    title: 'Sample Content'
    attributes:
      image: ''
      headline: 'headline 1'
      description: 'context 1'
      link: ''
      linktext: ''
      samples: {  }
  sample-9357:
    title: 'Sample Content'
    attributes:
      image: ''
      headline: ''
      description: "<p>\nLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.\n</p>"
      link: ''
      linktext: ''
      samples: {  }
  sample-3:
    title: 'Key Features'
    attributes:
      enabled: 0
      image: ''
      headline: 'Key Features'
      description: '<p>Gantry 5 is packed full of features created to empower the development of designs into fully functional layouts with the absolute minimum effort and fuss</p>'
      link: ''
      linktext: ''
      samples:
        -
          icon: 'fa fa-code'
          subtitle: ''
          description: '<p>Gantry 5 leverages the power of <a href="http://twig.sensiolabs.org/">Twig</a> to make creating powerful, dynamic themes quick and easy.</p>'
          title: 'Twig Templating'
        -
          icon: 'fa fa-newspaper-o'
          subtitle: ''
          description: '<p>Drag-and-drop functionality gives you the power to place content blocks, resize them, and configure their unique settings in seconds.</p>'
          title: 'Layout Manager'
        -
          icon: 'fa fa-cubes'
          subtitle: ''
          description: '<p>Create, configure, and manage content blocks as well as special features and functionality with the powerful particle system.</p>'
          title: 'Particles System'
  position-footer:
    attributes:
      key: footer
  copyright-2844:
    attributes:
      owner: 'Star Reisen'
  social-2031:
    attributes:
      css:
        class: social-items
      items:
        -
          icon: 'fa fa-twitter'
          text: Twitter
          title: ''
          link: 'http://starreisen.at'
          name: Twitter
        -
          icon: 'fa fa-facebook'
          text: Facebook
          title: ''
          link: 'http://starreisen.at'
          name: Facebook
        -
          icon: 'fa fa-google'
          text: Google
          title: ''
          link: 'http://starreisen.at'
          name: Google
    block:
      variations: center
  branding-8758:
    attributes:
      content: 'Powered by Joomla and <a href="http://www.gantry.org/" title="Gantry Framework" class="g-powered-by">Gantry Framework</a>'
    block:
      variations: align-right
  mobile-menu-7603:
    title: 'Mobile Menu'
