ordering:
  helium: ''
  ticket-buchen: ''
  aktuelles: ''
  kontakt: ''
items:
  helium:
    id: 105
    rel: ''
  ticket-buchen:
    id: 106
    rel: ''
    columns:
      - 100
  aktuelles:
    id: 109
    rel: ''
  kontakt:
    id: 107
    rel: ''
