version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1475608600
layout:
  /navigation/:
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
      - 'social-3171 20'
  /header/: {  }
  /intro/:
    -
      - owlcarousel-9471
    -
      - contentcubes-1730
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  /footer/:
    -
      - 'logo-9571 10'
      - 'copyright-1736 30'
      - 'horizontalmenu-9034 45'
      - 'totop-8670 15'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://starreisen_img/logo_104x62.png'
      svg: ''
      text: 'Starreisen Graz'
  social-3171:
    attributes:
      items:
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          title: ''
          link: 'https://www.facebook.com/StarReisenSeyahat'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          title: ''
          link: 'https://star-reisen.business.site/'
          name: Google+
        -
          icon: 'fa fa-instagram'
          text: ''
          title: ''
          link: 'https://www.instagram.com/star_reisen/'
          name: Instagram
    block:
      class: g-social-header
  owlcarousel-9471:
    title: 'Owl Carousel'
    attributes:
      class: ''
      title: ''
      nav: disable
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      imageOverlay: disable
      items:
        -
          class: ''
          image: 'gantry-media://starreisen_img/unnamed3.jpg'
          title: 'Jetzt buchen'
          desc: ''
          link: 'https://www.facebook.com/StarReisenSeyahat'
          linktext: 'Jetzt buchen'
          buttonclass: 'button button-gradient'
          disable: '0'
          name: 'Item 1'
        -
          class: ''
          image: 'gantry-media://starreisen_img/unnamed6.jpg'
          title: 'Jetzt buchen'
          desc: 'Günstig reisen'
          link: 'https://www.facebook.com/StarReisenSeyahat'
          linktext: 'Jetzt buchen'
          buttonclass: 'button button-gradient'
          disable: '0'
          name: 'Item 2'
        -
          class: ''
          image: 'gantry-media://starreisen_img/unnamed5.jpg'
          title: 'Jetzt buchen'
          desc: 'Jetzt buchen'
          link: 'https://www.facebook.com/StarReisenSeyahat'
          linktext: 'Jetzt buchen'
          buttonclass: 'button button-gradient'
          disable: '0'
          name: 'Item 3'
  contentcubes-1730:
    title: 'Content Cubes'
    attributes:
      css:
        class: ''
      title: ''
      items:
        -
          image: 'gantry-media://starreisen_img/pic1080x720.jpg'
          imageposition: left
          label: '👉 Die URLAUBS-EXPERTEN'
          title: ''
          tags:
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: 'Ihr Reisebüro in Graz |'
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: '⭐️ #STARREISEN'
            -
              text: '| FLUGTICKETS |'
            -
              text: 'BUSTICKETS Partner von FLIXBUS'
          link: ''
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: 'Item 1'
        -
          image: 'gantry-media://starreisen_img/pic_2_1080x720.jpg'
          imageposition: right
          label: '🏖 PAUSCHALREISEN & HOTELRESERV.'
          title: ''
          tags:
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: MIETWAGENSERVICE
            -
              text: '| 7/24 SERVICE |'
            -
              text: 'PERSÖNLICHE BERATUNG'
          link: ''
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: 'Item 2'
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
  logo-9571:
    title: 'Logo / Image'
    attributes:
      target: _self
      image: 'gantry-media://starreisen_img/logo_104x62.png'
      link: '1'
      svg: ''
  copyright-1736:
    attributes:
      date:
        start: '2007'
        end: now
      owner: ''
      additional:
        text: ''
  horizontalmenu-9034:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: Impressum
          link: '#'
          name: Impressum
        -
          text: Datenschutz
          link: '#'
          name: Datenschutz
        -
          text: Kontakt
          link: '#'
          name: Kontakt
  totop-8670:
    title: 'To Top'
    attributes:
      content: 'nach oben'
      title: 'nach oben'
