name: _offline
timestamp: 1590928134
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1590928134
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-3161: Logo
  spacer:
    spacer-6423: Spacer
    spacer-7830: Spacer
  messages:
    system-messages-8875: 'System Messages'
  content:
    system-content-3675: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-5375: Copyright
  branding:
    branding-3573: Branding
inherit: {  }
