version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1590928134
layout:
  /header/:
    -
      - 'logo-3161 30'
      - 'spacer-6423 70'
  /main/:
    -
      - system-messages-8875
    -
      - system-content-3675
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5375 40'
      - 'spacer-7830 30'
      - 'branding-3573 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
