name: 21
timestamp: 1619173198
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-6833: Header
    custom-9485: 'Equal Width Examples'
    custom-6522: 'Single Block per Row'
    custom-3772: 'Two Blocks per Row'
    custom-2813: 'Two Blocks per Row'
    custom-2874: 'Three Blocks per Row'
    custom-5117: 'Three Blocks per Row'
    custom-1891: 'Three Blocks per Row'
    custom-1030: 'Four Blocks per Row'
    custom-9108: 'Four Blocks per Row'
    custom-4617: 'Four Blocks per Row'
    custom-7536: 'Four Blocks per Row'
    custom-9267: 'Different Width Examples'
    custom-8260: '25% Width Block'
    custom-4188: '50% Width Block'
    custom-6944: '25% Width Block'
    custom-8585: '26% Width Block'
    custom-8036: '31% Width Block'
    custom-2331: '43% Width Block'
    custom-6361: 'Right Sidebar'
    custom-4736: Lipsum
    custom-5490: Content
    custom-9374: 'Flexible Layouts'
    custom-4266: Lipsum
  messages:
    system-messages-7562: 'System Messages'
  logo:
    logo-2543: 'Logo / Image'
    logo-2290: 'Logo / Image'
  menu:
    menu-6953: Menu
  social:
    social-5980: Social
  copyright:
    copyright-2441: Copyright
  horizontalmenu:
    horizontalmenu-4585: 'Horizontal Menu'
  totop:
    totop-7439: 'To Top'
  mobile-menu:
    mobile-menu-5725: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-7562: system-messages-7972
    logo-2543: logo-9608
    menu-6953: menu-6409
    social-5980: social-3171
    logo-2290: logo-9571
    copyright-2441: copyright-1736
    horizontalmenu-4585: horizontalmenu-9034
    totop-7439: totop-8670
    mobile-menu-5725: mobile-menu-5697
