ordering:
  helium: ''
  aktuelles: ''
  kontakt: ''
  features:
    particles: ''
    block-variations: ''
    typography: ''
    documentation: ''
    download: ''
  pages:
    blog-page: ''
    error-page: ''
    offline-page: ''
  sample-layouts:
    full-width: ''
    left-sidebar: ''
    right-sidebar: ''
    two-sidebars: ''
    two-sidebars-left: ''
    two-sidebars-right: ''
    rows-columns: ''
  styles:
    __particle-Ulbv2: ''
items:
  helium:
    id: 104
    rel: ''
  features:
    id: 106
    rel: ''
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  features/particles:
    id: 111
    rel: ''
  features/block-variations:
    id: 112
    rel: ''
  features/typography:
    id: 113
    rel: ''
  features/documentation:
    id: 109
    rel: ''
  features/download:
    id: 110
    rel: ''
  pages:
    id: 124
    rel: ''
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  pages/blog-page:
    id: 125
    rel: ''
  pages/error-page:
    id: 126
    rel: ''
  pages/offline-page:
    id: 127
    rel: ''
  sample-layouts:
    id: 107
    rel: ''
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  sample-layouts/full-width:
    id: 116
    rel: ''
  sample-layouts/left-sidebar:
    id: 117
    rel: ''
  sample-layouts/right-sidebar:
    id: 118
    rel: ''
  sample-layouts/two-sidebars:
    id: 119
    rel: ''
  sample-layouts/two-sidebars-left:
    id: 120
    rel: ''
  sample-layouts/two-sidebars-right:
    id: 121
    rel: ''
  sample-layouts/rows-columns:
    id: 122
    rel: ''
  styles:
    id: 108
    rel: ''
    attributes: {  }
    link_attributes: {  }
    dropdown: standard
    dropdown_dir: center
    dropdown_hide: '1'
    width: 35rem
  aktuelles:
    id: 129
    rel: ''
  kontakt:
    id: 131
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  styles/__particle-Ulbv2:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<div class=\"g-grid g-preset-thumbnails center\">\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset1\">\n                <img src=\"gantry-media://styles/preset1.png\" alt=\"Preset 1\">\n                <br />\n                <span>Preset 1</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset2\">\n                <img src=\"gantry-media://styles/preset2.png\" alt=\"Preset 2\">\n                <br />\n                <span>Preset 2</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset3\">\n                <img src=\"gantry-media://styles/preset3.png\" alt=\"Preset 3\">\n                <br />\n                <span>Preset 3</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset4\">\n                <img src=\"gantry-media://styles/preset4.png\" alt=\"Preset 4\">\n                <br />\n                <span>Preset 4</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset5\">\n                <img src=\"gantry-media://styles/preset5.png\" alt=\"Preset 5\">\n                <br />\n                <span>Preset 5</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset6\">\n                <img src=\"gantry-media://styles/preset6.png\" alt=\"Preset 6\">\n                <br />\n                <span>Preset 6</span>\n            </a>\n        </div>\n    </div>    \n</div>"
      block:
        extra: {  }
    enabled: true
    anchor_class: ''
