name: '12'
timestamp: 1590928134
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1590928134
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3841: Logo
    logo-7581: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
    position-position-8771: Header
    position-position-7672: Breadcrumbs
    position-position-5926: Footer
  menu:
    menu-4633: Menu
    menu-5014: Menu
  messages:
    system-messages-5763: 'System Messages'
    system-messages-3690: 'System Messages'
  content:
    system-content-4780: 'Page Content'
    system-content-8357: 'Page Content'
  copyright:
    copyright-5565: Copyright
    copyright-4494: Copyright
  spacer:
    spacer-3578: Spacer
    spacer-5725: Spacer
  branding:
    branding-4442: Branding
    branding-1051: Branding
  mobile-menu:
    mobile-menu-5694: Mobile-menu
    mobile-menu-6567: Mobile-menu
inherit:
  default:
    header: header
    logo-3841: logo-3841
    position-header: position-header
    navigation: navigation
    menu-4633: menu-4633
    main: main
    position-breadcrumbs: position-breadcrumbs
    system-messages-5763: system-messages-5763
    system-content-4780: system-content-4780
    footer: footer
    position-footer: position-footer
    copyright-5565: copyright-5565
    spacer-3578: spacer-3578
    branding-4442: branding-4442
    offcanvas: offcanvas
    mobile-menu-5694: mobile-menu-5694
    logo-7581: logo-3841
    position-position-8771: position-header
    menu-5014: menu-4633
    position-position-7672: position-breadcrumbs
    system-messages-3690: system-messages-5763
    system-content-8357: system-content-4780
    position-position-5926: position-footer
    copyright-4494: copyright-5565
    spacer-5725: spacer-3578
    branding-1051: branding-4442
    mobile-menu-6567: mobile-menu-5694
