name: 12
timestamp: 1616607569
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1590928134
positions: {  }
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles: {  }
inherit:
  default:
    header: header
    navigation: navigation
    main: main
    footer: footer
    offcanvas: offcanvas
