version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1590928134
layout:
  /header/:
    -
      - 'logo-5778 30'
      - 'spacer-8568 70'
  /navigation/:
    -
      - menu-7534
  /main/:
    -
      - system-content-3703
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3553 40'
      - 'spacer-8061 30'
      - 'branding-5480 30'
  offcanvas:
    -
      - mobile-menu-4292
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
