name: _body_only
timestamp: 1590928134
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1590928134
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-9011: 'System Messages'
  content:
    system-content-6044: 'Page Content'
inherit: {  }
