version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1590928134
layout:
  /main/:
    -
      - system-messages-9011
    -
      - system-content-6044
structure:
  main:
    attributes:
      boxed: ''
